# Cargo configuration file for OptiVorbis.
# Reference: https://doc.rust-lang.org/cargo/reference/config.html
# This file is primarily useful for specifying custom rustflags

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg",
  'getrandom_backend="wasm_js"',
  "-Zunstable-options",
  "-Cpanic=immediate-abort",
]
