# Cargo configuration file for OptiVorbis.
# Reference: https://doc.rust-lang.org/cargo/reference/config.html
# This file is primarily useful for specifying custom rustflags

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))']
linker = 'aarch64-linux-gnu-gcc'
runner = 'qemu-aarch64'

[target.aarch64-unknown-linux-gnu]
runner = ['qemu-aarch64', '/usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1']
