[package]
name = "optivorbis_afl_fuzz_target"
description = "Fuzzing target for OptiVorbis and afl.rs"
version = "0.0.1"
edition.workspace = true
publish = false

[dependencies]
optivorbis.workspace = true
afl = "0.15.1"
