[package]
name = "optivorbis_afl_fuzz_target"
description = "Fuzzing target for OptiVorbis and afl.rs"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
optivorbis.workspace = true
afl = "0.13.2"
