[package]
name = "optivorbis_afl_fuzz_target"
description = "Fuzzing target for OptiVorbis and afl.rs"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
optivorbis = { version = "0.1.1", path = "../optivorbis" }
afl = "0.12.15"
