[package]
name = "optivorbis_afl_fuzz_target"
edition.workspace = true
description = "Fuzzing target for OptiVorbis and afl.rs"
publish = false

[dependencies]
afl.workspace = true
optivorbis.workspace = true
