[package]
name = "optivorbis_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Command-line interface application for lossless Vorbis optimization and repair"
readme = "../../README.md"
homepage.workspace = true
repository.workspace = true
license = "AGPL-3.0-or-later"
keywords.workspace = true
categories.workspace = true
publish = false

[[bin]]
# This binary target has the same name as the main library target.
# In general, Cargo does not support that, but it is only troublesome
# for us when running rustdoc, as the binary and library executables
# do not clash otherwise. See:
# https://github.com/rust-lang/cargo/issues/6313
# This binary crate is straightforward enough to not need documentation,
# so let's just not document it.
doc = false
name = "optivorbis"

[dependencies]
getopts.workspace = true
log.workspace = true
optivorbis.workspace = true
stderrlog.workspace = true
