[package]
name = "optivorbis_cli"
description = "Command-line interface application for lossless Vorbis optimization and repair"
authors.workspace = true
license = "AGPL-3.0-or-later"
version.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true
edition.workspace = true
publish = false

[dependencies]
optivorbis.workspace = true

getopts = "0.2.21"
log.workspace = true
stderrlog = { version = "0.5.4", default-features = false }

[[bin]]
name = "optivorbis"
# This binary target has the same name as the main library target.
# In general, Cargo does not support that, but it is only troublesome
# for us when running rustdoc, as the binary and library executables
# do not clash otherwise. See:
# https://github.com/rust-lang/cargo/issues/6313
# This binary crate is straightforward enough to not need documentation,
# so let's just not document it.
doc = false
