name: CI

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - gh-pages
  release:
    types:
      - published

env:
  MSRV: "1.94.0"

  # Deny warnings on CI without invalidating build caches, see:
  # https://blog.rust-lang.org/2026/07/09/Rust-1.97.0/#cargo-support-for-denying-warnings
  CARGO_BUILD_WARNINGS: deny

permissions:
  contents: read # For checking out the repository

concurrency:
  group: ci-${{ github.event_name }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  msrv_check:
    name: MSRV check

    runs-on: ubuntu-26.04

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    permissions:
      contents: write # For writing to GHA cache

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: 🧰 Install MSRV toolchain
        uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # v1
        with:
          toolchain: ${{ env.MSRV }}

      - name: 💨 Set up sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

      - name: 💨 Configure sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'RUSTC_WRAPPER=sccache' >> "$GITHUB_ENV"
          echo 'SCCACHE_GHA_ENABLED=true' >> "$GITHUB_ENV"

      - name: ⚙️ Run tests
        run: cargo test -p optivorbis -p optivorbis_cli -p vorbis_bitpack

  ci:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-musl
            runner: ubuntu-26.04
          - target: aarch64-unknown-linux-musl
            runner: ubuntu-26.04-arm
          - target: x86_64-pc-windows-gnu
            runner: windows-2025
          - target: x86_64-apple-darwin
            runner: macos-26
          - target: aarch64-apple-darwin
            runner: macos-26

    name: CI (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    permissions:
      security-events: write # For uploading SARIF static analysis results

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # Keep the commit history for proper version information
          persist-credentials: false

      - name: 🧰 Install Rust toolchain
        uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296 # nightly
        with:
          target: ${{ matrix.target }}
          components: rust-src, rustfmt, clippy

      - name: 🧰 Install static analysis and documentation tools
        if: matrix.target == 'x86_64-unknown-linux-musl'
        uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172 # v2
        with:
          tool: cargo-deny,cargo-docs-rs,clippy-sarif,sarif-fmt

      - name: 💨 Set up sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

      - name: 💨 Configure sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'RUSTC_WRAPPER=sccache' >> "$GITHUB_ENV"
          echo 'SCCACHE_GHA_ENABLED=true' >> "$GITHUB_ENV"

      - name: 📅 Gather build date and version metadata
        shell: bash
        run: |
          echo "OPTIVORBIS_VERSION=$(git describe --tags --dirty=-custom --always)" >> "$GITHUB_ENV"
          echo "OPTIVORBIS_BUILD_DATE=$(date -u +%Y-%m-%d)" >> "$GITHUB_ENV"

      - name: "🔍 Static analysis: run Clippy"
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          set -o pipefail
          cargo clippy --no-deps --all-targets --all-features --keep-going --message-format=json \
            | clippy-sarif \
            | tee /tmp/clippy-results.sarif \
            | sarif-fmt

      - name: "🔍 Static analysis: run rustfmt"
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cargo fmt --check --all

      - name: "🔍 Static analysis: run cargo deny"
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: cargo deny check

      - name: ✔️ Run tests
        run: cargo test --target ${{ matrix.target }}
          -p optivorbis -p optivorbis_cli -p vorbis_bitpack

      - name: 📚 Build documentation
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          cargo docs-rs -p optivorbis
          cargo docs-rs -p vorbis_bitpack
          cargo doc --workspace --no-deps

      - name: 🔨 Build CLI executable
        env:
          RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
        run: cargo build --target ${{ matrix.target }} --release
          -Z build-std=panic_abort,core,std,alloc,proc_macro
          -Z build-std-features=

      - name: 📤 Upload CLI executable artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: OptiVorbis CLI (${{ matrix.target }})
          path: |
            target/${{ matrix.target }}/release/optivorbis
            target/${{ matrix.target }}/release/optivorbis.exe

      - name: 📤 Upload Clippy static analysis results
        if: always() && matrix.target == 'x86_64-unknown-linux-musl'
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        continue-on-error: true
        with:
          sarif_file: /tmp/clippy-results.sarif
          category: clippy

  web_demo:
    name: Web demo

    needs: ci
    runs-on: ubuntu-26.04

    # Exclude in-repo PRs from running this job
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork

    defaults:
      run:
        working-directory: web

    permissions:
      contents: write # For deploying to GitHub Pages

    steps:
      - name: 📥 Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # Keep the commit history for proper version information
          persist-credentials: false

      - name: 🧰 Install Rust toolchain
        uses: dtolnay/rust-toolchain@be39649afda95dbf70f87cce95f68b8d5797b296 # nightly
        with:
          components: rust-src

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          package-manager-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}

      - name: 💨 Set up sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11

      - name: 💨 Configure sccache
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'RUSTC_WRAPPER=sccache' >> "$GITHUB_ENV"
          echo 'SCCACHE_GHA_ENABLED=true' >> "$GITHUB_ENV"

      - name: 🧰 Install wasm-pack
        uses: taiki-e/install-action@9983c65e42da123ff25d1f78505eb6de315aa172 # v2
        with:
          tool: wasm-pack

      - name: 📅 Gather build date and version metadata
        shell: bash
        run: |
          echo "OPTIVORBIS_VERSION=$(git describe --tags --dirty=-custom --always)" >> "$GITHUB_ENV"
          echo "OPTIVORBIS_BUILD_DATE=$(date -u +%Y-%m-%d)" >> "$GITHUB_ENV"

      - name: 🔨 Build web demo
        run: npm ci && npm run build

      - name: "🔍 Static analysis: ESLint"
        run: npm run lint

      - name: 📤 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        if: github.ref == 'refs/heads/master' # Only run for pushes to the master branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/web
